# 17/11/22

Date time data

In [2]:
import pandas as pd 
import numpy as np
import seaborn as sns

In [3]:
df=pd.read_excel("C:\\Users\\rupan\\OneDrive\\Desktop\\data_sets\\catalog.xlsx")
df

id                 date      time continent_code   country_name  \
0       34  2007-02-03 00:00:00     Night            NaN  United States   
1       42              3/22/07       NaN            NaN  United States   
2       56  2007-06-04 00:00:00       NaN            NaN  United States   
3       59              4/14/07       NaN            NaN         Canada   
4       61              4/15/07       NaN            NaN  United States   
...    ...                  ...       ...            ...            ...   
1688  7535  2015-07-12 00:00:00       NaN            NaN  United States   
1689  7537              2/22/16  00:00:00            NaN  United States   
1690  7539              2/23/16       NaN            NaN  United States   
1691  7540              2/26/16  21:06:00            NaN  United States   
1692  7541  2016-02-03 00:00:00  08:00:00            NaN  United States   

     country_code  state/province  population         city/town  distance  \
0              US        Virginia       16000       Cherry Hill   3.40765   
1              US            Ohio       17288  New Philadelphia   3.33522   
2              US    Pennsylvania       15930       Wilkinsburg   2.91977   
3              CA          Quebec       42786      Châteauguay   2.98682   
4              US        Kentucky        6903         Pikeville   5.66542   
...           ...             ...         ...               ...       ...   
1688           US  North Carolina        1646             Tryon   7.80866   
1689           US   West Virginia       51400        Charleston   6.84721   
1690           US   West Virginia        2406             Welch  14.19735   
1691           US   West Virginia        1048            Athens  12.00678   
1692           US         Vermont        2066           Windsor   1.78429   

      ...                                geolocation  hazard_type  \
0     ...  (38.600900000000003, -77.268199999999993)    Landslide   
1     ...  (40.517499999999998, -81.430499999999995)    Landslide   
2     ...             (40.4377, -79.915999999999997)    Landslide   
3     ...  (45.322600000000001, -73.777100000000004)    Landslide   
4     ...  (37.432499999999997, -82.493099999999998)    Landslide   
...   ...                                        ...          ...   
1688  ...  (35.221899999999998, -82.322599999999994)    Landslide   
1689  ...  (38.398699999999998, -81.584800000000001)    Landslide   
1690  ...             (37.409599999999998, -81.4268)    Landslide   
1691  ...  (37.501100000000001, -81.109300000000005)    Landslide   
1692  ...             (43.4771, -72.406599999999997)    Landslide   

          landslide_type landslide_size   trigger storm_name injuries  \
0              Landslide          Small      Rain        NaN      NaN   
1              Landslide          Small      Rain        NaN      NaN   
2              Landslide          Small      Rain        NaN      NaN   
3     Riverbank collapse          Small      Rain        NaN      NaN   
4              Landslide          Small  Downpour        NaN      NaN   
...                  ...            ...       ...        ...      ...   
1688            Rockfall          Small       NaN        NaN      0.0   
1689            Mudslide          Small   Unknown        NaN      0.0   
1690           Landslide          Small      Rain        NaN      0.0   
1691            Rockfall          Small   Unknown        NaN      0.0   
1692            Rockfall          Small   Unknown        NaN      0.0   

     fatalities                 source_name  \
0           NaN                  NBC 4 news   
1           NaN              Canton Rep.com   
2           NaN  The Pittsburgh Channel.com   
3           NaN                   Le Soleil   
4           0.0      Matthew Crawford (KGS)   
...         ...                         ...   
1688        0.0        Tryon Daily Bulletin   
1689        0.0          Charleston Gazette   
1690        0.0   Bluefield Daily Telegraph   
1691  

In [5]:
# check date type first always
df.info() 
# first convert it into data-time type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1693 entries, 0 to 1692
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   id                    1693 non-null   int64  
 1   date                  1690 non-null   object 
 2   time                  629 non-null    object 
 3   continent_code        164 non-null    object 
 4   country_name          1693 non-null   object 
 5   country_code          1693 non-null   object 
 6   state/province        1692 non-null   object 
 7   population            1693 non-null   int64  
 8   city/town             1689 non-null   object 
 9   distance              1692 non-null   float64
 10  location_description  551 non-null    object 
 11  latitude              1692 non-null   float64
 12  longitude             1692 non-null   float64
 13  geolocation           1692 non-null   object 
 14  hazard_type           1693 non-null   object 
 15  landslide_type       

In [6]:
df.isnull().sum()

id                         0
date                       3
time                    1064
continent_code          1529
country_name               0
country_code               0
state/province             1
population                 0
city/town                  4
distance                   1
location_description    1142
latitude                   1
longitude                  1
geolocation                1
hazard_type                0
landslide_type             1
landslide_size             1
trigger                    2
storm_name              1561
injuries                1178
fatalities               247
source_name              821
source_link              100
dtype: int64

In [7]:
#called filling or imputing

In [9]:
df["date"].fillna(df["date"].mode()[0],inplace=True)  
#mode can have more than one repetitive value, we want first entry so we gave index[0]

In [10]:
df.isnull().sum()

id                         0
date                       0
time                    1064
continent_code          1529
country_name               0
country_code               0
state/province             1
population                 0
city/town                  4
distance                   1
location_description    1142
latitude                   1
longitude                  1
geolocation                1
hazard_type                0
landslide_type             1
landslide_size             1
trigger                    2
storm_name              1561
injuries                1178
fatalities               247
source_name              821
source_link              100
dtype: int64

In [11]:
# converting date to datetime datatype
df["date"]=pd.to_datetime(df["date"])

In [13]:
df.dtypes

id                               int64
date                    datetime64[ns]
time                            object
continent_code                  object
country_name                    object
country_code                    object
state/province                  object
population                       int64
city/town                       object
distance                       float64
location_description            object
latitude                       float64
longitude                      float64
geolocation                     object
hazard_type                     object
landslide_type                  object
landslide_size                  object
trigger                         object
storm_name                      object
injuries                       float64
fatalities                     float64
source_name                     object
source_link                     object
dtype: object

In [14]:
#df.drop(columns=["continent_code","state/province","city/town","distance","location_description","latitude","longitude","geolocation","landslide_size","trigger","storm_name","injuries","fatalities","source_name","source_link"])

In [15]:
df.drop(columns=["continent_code","location_description","source_link","source_name","fatalities","storm_name","injuries","city/town","distance","latitude","longitude","landslide_size","trigger"],inplace=True)

In [16]:
df

id       date      time   country_name country_code  state/province  \
0       34 2007-02-03     Night  United States           US        Virginia   
1       42 2007-03-22       NaN  United States           US            Ohio   
2       56 2007-06-04       NaN  United States           US    Pennsylvania   
3       59 2007-04-14       NaN         Canada           CA          Quebec   
4       61 2007-04-15       NaN  United States           US        Kentucky   
...    ...        ...       ...            ...          ...             ...   
1688  7535 2015-07-12       NaN  United States           US  North Carolina   
1689  7537 2016-02-22  00:00:00  United States           US   West Virginia   
1690  7539 2016-02-23       NaN  United States           US   West Virginia   
1691  7540 2016-02-26  21:06:00  United States           US   West Virginia   
1692  7541 2016-02-03  08:00:00  United States           US         Vermont   

      population                                geolocation hazard_type  \
0          16000  (38.600900000000003, -77.268199999999993)   Landslide   
1          17288  (40.517499999999998, -81.430499999999995)   Landslide   
2          15930             (40.4377, -79.915999999999997)   Landslide   
3          42786  (45.322600000000001, -73.777100000000004)   Landslide   
4           6903  (37.432499999999997, -82.493099999999998)   Landslide   
...          ...                                        ...         ...   
1688        1646  (35.221899999999998, -82.322599999999994)   Landslide   
1689       51400  (38.398699999999998, -81.584800000000001)   Landslide   
1690        2406             (37.409599999999998, -81.4268)   Landslide   
1691        1048  (37.501100000000001, -81.109300000000005)   Landslide   
1692        2066             (43.4771, -72.406599999999997)   Landslide   

          landslide_type  
0              Landslide  
1              Landslide  
2              Landslide  
3     Riverbank collapse  
4              Landslide  
...                  ...  
1688            Rockfall  
1689            Mudslide  
1690           Landslide  
1691            Rockfall  
1692            Rockfall  

[1693 rows x 10 columns]

In [17]:
df.isnull().sum()

id                   0
date                 0
time              1064
country_name         0
country_code         0
state/province       1
population           0
geolocation          1
hazard_type          0
landslide_type       1
dtype: int64

In [21]:
df["landslide_type"].fillna(df["landslide_type"].mode()[0],inplace=True)

In [22]:
from datetime import datetime as dt  # dt is alias

In [23]:
#creating a new column name year and extracting year from date column
df["year"]=df.date.dt.year
df

id       date      time   country_name country_code  state/province  \
0       34 2007-02-03     Night  United States           US        Virginia   
1       42 2007-03-22       NaN  United States           US            Ohio   
2       56 2007-06-04       NaN  United States           US    Pennsylvania   
3       59 2007-04-14       NaN         Canada           CA          Quebec   
4       61 2007-04-15       NaN  United States           US        Kentucky   
...    ...        ...       ...            ...          ...             ...   
1688  7535 2015-07-12       NaN  United States           US  North Carolina   
1689  7537 2016-02-22  00:00:00  United States           US   West Virginia   
1690  7539 2016-02-23       NaN  United States           US   West Virginia   
1691  7540 2016-02-26  21:06:00  United States           US   West Virginia   
1692  7541 2016-02-03  08:00:00  United States           US         Vermont   

      population                                geolocation hazard_type  \
0          16000  (38.600900000000003, -77.268199999999993)   Landslide   
1          17288  (40.517499999999998, -81.430499999999995)   Landslide   
2          15930             (40.4377, -79.915999999999997)   Landslide   
3          42786  (45.322600000000001, -73.777100000000004)   Landslide   
4           6903  (37.432499999999997, -82.493099999999998)   Landslide   
...          ...                                        ...         ...   
1688        1646  (35.221899999999998, -82.322599999999994)   Landslide   
1689       51400  (38.398699999999998, -81.584800000000001)   Landslide   
1690        2406             (37.409599999999998, -81.4268)   Landslide   
1691        1048  (37.501100000000001, -81.109300000000005)   Landslide   
1692        2066             (43.4771, -72.406599999999997)   Landslide   

          landslide_type  year  
0              Landslide  2007  
1              Landslide  2007  
2              Landslide  2007  
3     Riverbank collapse  2007  
4              Landslide  2007  
...                  ...   ...  
1688            Rockfall  2015  
1689            Mudslide  2016  
1690           Landslide  2016  
1691            Rockfall  2016  
1692            Rockfall  2016  

[1693 rows x 11 columns]

In [25]:
#df.head()

In [26]:
df["year"].unique()

array([2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016],
      dtype=int64)

In [28]:
#extracting month
df["month"]=df.date.dt.month
df

id       date      time   country_name country_code  state/province  \
0       34 2007-02-03     Night  United States           US        Virginia   
1       42 2007-03-22       NaN  United States           US            Ohio   
2       56 2007-06-04       NaN  United States           US    Pennsylvania   
3       59 2007-04-14       NaN         Canada           CA          Quebec   
4       61 2007-04-15       NaN  United States           US        Kentucky   
...    ...        ...       ...            ...          ...             ...   
1688  7535 2015-07-12       NaN  United States           US  North Carolina   
1689  7537 2016-02-22  00:00:00  United States           US   West Virginia   
1690  7539 2016-02-23       NaN  United States           US   West Virginia   
1691  7540 2016-02-26  21:06:00  United States           US   West Virginia   
1692  7541 2016-02-03  08:00:00  United States           US         Vermont   

      population                                geolocation hazard_type  \
0          16000  (38.600900000000003, -77.268199999999993)   Landslide   
1          17288  (40.517499999999998, -81.430499999999995)   Landslide   
2          15930             (40.4377, -79.915999999999997)   Landslide   
3          42786  (45.322600000000001, -73.777100000000004)   Landslide   
4           6903  (37.432499999999997, -82.493099999999998)   Landslide   
...          ...                                        ...         ...   
1688        1646  (35.221899999999998, -82.322599999999994)   Landslide   
1689       51400  (38.398699999999998, -81.584800000000001)   Landslide   
1690        2406             (37.409599999999998, -81.4268)   Landslide   
1691        1048  (37.501100000000001, -81.109300000000005)   Landslide   
1692        2066             (43.4771, -72.406599999999997)   Landslide   

          landslide_type  year  month  
0              Landslide  2007      2  
1              Landslide  2007      3  
2              Landslide  2007      6  
3     Riverbank collapse  2007      4  
4              Landslide  2007      4  
...                  ...   ...    ...  
1688            Rockfall  2015      7  
1689            Mudslide  2016      2  
1690           Landslide  2016      2  
1691            Rockfall  2016      2  
1692            Rockfall  2016      2  

[1693 rows x 12 columns]

In [29]:
# extracting month name
df["m_name"]=df.date.dt.month_name()
df["m_name"]

0       February
1          March
2           June
3          April
4          April
          ...   
1688        July
1689    February
1690    February
1691    February
1692    February
Name: m_name, Length: 1693, dtype: object

In [30]:
df["m_name"].unique()

array(['February', 'March', 'June', 'April', 'May', 'January', 'August',
       'July', 'September', 'November', 'December', 'October'],
      dtype=object)

In [31]:
#extracting day
df["day"]=df.date.dt.day
df["day"].unique()

array([ 3, 22,  4, 14, 15, 20, 24, 21, 27,  7, 13,  8, 17, 18, 19, 23,  9,
       28, 10, 29, 31, 11, 30, 12, 16,  1,  2, 25,  5,  6, 26],
      dtype=int64)

In [32]:
#extracting dayname
df["day_name"]=df.date.dt.day_name()
df["day_name"].unique()

array(['Saturday', 'Thursday', 'Monday', 'Sunday', 'Friday', 'Tuesday',
       'Wednesday'], dtype=object)

In [33]:
#extracting day of week
df["d_week"]=df.date.dt.dayofweek
df["d_week"].unique()

array([5, 3, 0, 6, 4, 1, 2], dtype=int64)

In [34]:
#extracting  week of year
df["week_no"]=df.date.dt.week
df["week_no"].unique()

C:\Users\rupan\AppData\Local\Temp\ipykernel_26744\1770653043.py:2: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  df["week_no"]=df.date.dt.week


array([ 5, 12, 23, 15, 16, 17, 21, 26,  1, 14, 32, 28, 30, 36, 45, 33, 34,
        2,  6, 10, 19, 38, 39, 37, 50, 41, 42, 43, 44, 46, 48, 51, 22, 27,
       18,  9, 40, 11, 13, 49, 25, 29, 31, 35, 24, 47, 52,  4, 20, 53,  3,
        7,  8], dtype=int64)

In [35]:
# extracting weekend   #1 is for weekend and o is for weekdays
import numpy as np
df["date is weekend"]=np.where(df["day_name"].isin(["Sunday","Saturday"]),1,0)
df["date is weekend"]

0       1
1       0
2       0
3       1
4       1
       ..
1688    1
1689    0
1690    0
1691    0
1692    0
Name: date is weekend, Length: 1693, dtype: int32

In [36]:
# extracting quarter
df["quarter"]=df.date.dt.quarter
df["quarter"].unique()

array([1, 2, 3, 4], dtype=int64)

In [38]:
df["time"].fillna(df["time"].mode()[0],inplace=True)

In [39]:
df["time"]

0          Night
1          Night
2          Night
3          Night
4          Night
          ...   
1688       Night
1689    00:00:00
1690       Night
1691    21:06:00
1692    08:00:00
Name: time, Length: 1693, dtype: object

In [40]:
df["time"].dtype

dtype('O')

In [44]:
#df["time"]=pd.to_datetime(df["time"])

In [45]:
## current date and time
import datetime
today=datetime.datetime.today()
today

datetime.datetime(2022, 11, 17, 11, 24, 22, 238688)

In [46]:
today-df["date"]

0      5766 days 11:24:22.238688
1      5719 days 11:24:22.238688
2      5645 days 11:24:22.238688
3      5696 days 11:24:22.238688
4      5695 days 11:24:22.238688
                  ...           
1688   2685 days 11:24:22.238688
1689   2460 days 11:24:22.238688
1690   2459 days 11:24:22.238688
1691   2456 days 11:24:22.238688
1692   2479 days 11:24:22.238688
Name: date, Length: 1693, dtype: timedelta64[ns]

In [48]:
## month difference
np.round((today-df["date"])/np.timedelta64(1,"M"),0)

0       189.0
1       188.0
2       185.0
3       187.0
4       187.0
        ...  
1688     88.0
1689     81.0
1690     81.0
1691     81.0
1692     81.0
Name: date, Length: 1693, dtype: float64

In [49]:
df["time"]=df["date"].dt.time
df

id       date      time   country_name country_code  state/province  \
0       34 2007-02-03  00:00:00  United States           US        Virginia   
1       42 2007-03-22  00:00:00  United States           US            Ohio   
2       56 2007-06-04  00:00:00  United States           US    Pennsylvania   
3       59 2007-04-14  00:00:00         Canada           CA          Quebec   
4       61 2007-04-15  00:00:00  United States           US        Kentucky   
...    ...        ...       ...            ...          ...             ...   
1688  7535 2015-07-12  00:00:00  United States           US  North Carolina   
1689  7537 2016-02-22  00:00:00  United States           US   West Virginia   
1690  7539 2016-02-23  00:00:00  United States           US   West Virginia   
1691  7540 2016-02-26  00:00:00  United States           US   West Virginia   
1692  7541 2016-02-03  00:00:00  United States           US         Vermont   

      population                                geolocation hazard_type  \
0          16000  (38.600900000000003, -77.268199999999993)   Landslide   
1          17288  (40.517499999999998, -81.430499999999995)   Landslide   
2          15930             (40.4377, -79.915999999999997)   Landslide   
3          42786  (45.322600000000001, -73.777100000000004)   Landslide   
4           6903  (37.432499999999997, -82.493099999999998)   Landslide   
...          ...                                        ...         ...   
1688        1646  (35.221899999999998, -82.322599999999994)   Landslide   
1689       51400  (38.398699999999998, -81.584800000000001)   Landslide   
1690        2406             (37.409599999999998, -81.4268)   Landslide   
1691        1048  (37.501100000000001, -81.109300000000005)   Landslide   
1692        2066             (43.4771, -72.406599999999997)   Landslide   

          landslide_type  year  month    m_name  day   day_name  d_week  \
0              Landslide  2007      2  February    3   Saturday       5   
1              Landslide  2007      3     March   22   Thursday       3   
2              Landslide  2007      6      June    4     Monday       0   
3     Riverbank collapse  2007      4     April   14   Saturday       5   
4              Landslide  2007      4     April   15     Sunday       6   
...                  ...   ...    ...       ...  ...        ...     ...   
1688            Rockfall  2015      7      July   12     Sunday       6   
1689            Mudslide  2016      2  February   22     Monday       0   
1690           Landslide  2016      2  February   23    Tuesday       1   
1691            Rockfall  2016      2  February   26     Friday       4   
1692            Rockfall  2016      2  February    3  Wednesday       2   

      week_no  date is weekend  quarter  
0           5                1        1  
1          12                0        1  
2          23                0        2  
3          15                1        2  
4          15                1        2  
...       ...              ...      ...  
1688       28                1        3  
1689        8                0        1  
1690        8                0        1  
1691        8                0        1  
1692        5                0        1  

[1693 rows x 19 columns]

In [52]:
# how many landslide happen year-wise
df.groupby(["year"])["landslide_type"].value_counts().sort_values(ascending=False)

year  landslide_type    
2010  Landslide             179
2015  Landslide             154
2011  Landslide             154
2010  Mudslide              132
2013  Mudslide              127
      Landslide             123
2011  Mudslide              116
2014  Landslide             104
2015  Mudslide               73
2014  Mudslide               66
2012  Landslide              48
2008  Mudslide               48
      Landslide              42
2007  Landslide              40
2009  Mudslide               34
2007  Mudslide               21
2010  Complex                20
2015  Rockfall               20
2009  Landslide              18
2012  Mudslide               17
2013  Debris flow            15
2016  Rockfall               13
2008  Complex                10
2014  Rockfall               10
2007  Complex                 9
2010  Rockfall                9
2015  Other                   9
2009  Rockfall                8
2014  Debris flow             6
2013  Rockfall                6
2011  Complex  

In [53]:
date=pd.date_range("1/1/2000",periods=12,freq="M")  ## date range is a pandas function to generate dates 
date   #now its giving output in month difference


DatetimeIndex(['2000-01-31', '2000-02-29', '2000-03-31', '2000-04-30',
               '2000-05-31', '2000-06-30', '2000-07-31', '2000-08-31',
               '2000-09-30', '2000-10-31', '2000-11-30', '2000-12-31'],
              dtype='datetime64[ns]', freq='M')